const fs = require("fs");
const path = require("path");
const SEGMENTS_X = 64;
const SEGMENTS_Y = 48;
const RADIUS = 1.0;

function noise3D(x, y, z) {
  return (
    Math.sin(x * 12.9898 + y * 78.233 + z * 45.164) * 43758.5453 % 1
  );
}

function generateBrainMesh() {
  const vertices = [];
  const normals = [];
  const faces = [];

  for (let iy = 0; iy <= SEGMENTS_Y; iy++) {
    const v = iy / SEGMENTS_Y;
    const phi = v * Math.PI;

    for (let ix = 0; ix <= SEGMENTS_X; ix++) {
      const u = ix / SEGMENTS_X;
      const theta = u * Math.PI * 2;

      let x = -RADIUS * Math.cos(theta) * Math.sin(phi);
      let y = RADIUS * Math.cos(phi);
      let z = RADIUS * Math.sin(theta) * Math.sin(phi);

      z *= 1.15;

      const temple = Math.exp(-((y - 0.1) ** 2) / 0.15);
      x *= 1.0 + temple * 0.08;

      if (y > 0.6) {
        y = 0.6 + (y - 0.6) * 0.5;
      }

      const midlineFactor = Math.exp(-(x * x) / 0.01);
      if (y > 0.2) {
        y -= midlineFactor * 0.06 * Math.max(0, y - 0.2);
      }

      const freq1 = Math.sin(x * 12) * Math.cos(y * 10) * Math.sin(z * 11);
      const freq2 = Math.sin(x * 20 + 1.3) * Math.cos(z * 18 + 0.7);
      const freq3 = Math.cos(y * 25 + 2.1) * Math.sin(x * 15 - 1.5);
      const freq4 = Math.sin(x * 8 + z * 6) * Math.cos(y * 14 + 3.0);
      const displacement =
        freq1 * 0.035 + freq2 * 0.02 + freq3 * 0.015 + freq4 * 0.012;

      const len = Math.sqrt(x * x + y * y + z * z);
      if (len > 0) {
        const scale = (len + displacement) / len;
        x *= scale;
        y *= scale;
        z *= scale;
      }
      if (y < -0.7) {
        y = -0.7 + (y + 0.7) * 0.3;
      }

      vertices.push([x, y, z]);

      const nLen = Math.sqrt(x * x + y * y + z * z) || 1;
      normals.push([x / nLen, y / nLen, z / nLen]);
    }
  }

  for (let iy = 0; iy < SEGMENTS_Y; iy++) {
    for (let ix = 0; ix < SEGMENTS_X; ix++) {
      const a = iy * (SEGMENTS_X + 1) + ix + 1;
      const b = a + 1;
      const c = a + (SEGMENTS_X + 1);
      const d = c + 1;

      if (iy !== 0) {
        faces.push([a, b, d]);
      }
      if (iy !== SEGMENTS_Y - 1) {
        faces.push([a, d, c]);
      }
    }
  }

  return { vertices, normals, faces };
}

function toOBJ({ vertices, normals, faces }) {
  const lines = [
    "# Brain surface mesh - generated by CortexFlow",
    `# Vertices: ${vertices.length}, Faces: ${faces.length}`,
    "",
  ];

  for (const [x, y, z] of vertices) {
    lines.push(`v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}`);
  }
  lines.push("");

  for (const [x, y, z] of normals) {
    lines.push(`vn ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}`);
  }
  lines.push("");

  for (const [a, b, c] of faces) {
    lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
  }
  return lines.join("\n");
}

const mesh = generateBrainMesh();
const obj = toOBJ(mesh);
const outPath = path.join(__dirname, "..", "public", "cortexflow_surface_mesh.obj");
fs.writeFileSync(outPath, obj);
console.log(`Wrote ${outPath} (${vertices(mesh)} verts, ${mesh.faces.length} faces)`);

function vertices(m) { return m.vertices.length; }
